views:
  - title: 场景切换
    path: ''
    badges: []
    cards:
      - type: grid
        square: false
        columns: 1
        cards: []
  - title: 全屋户型-灯光
    path: wq-11w
    badges: []
    cards:
      - type: picture-elements
        image: /local/house/wansh-0.png
        elements:
          - type: state-badge
            entity: sensor.liaoliaode_jia_gan_jue_wen_du
            title: 室内温度
            style:
              top: 15%
              left: 7%
          - type: image
            entity: light.hyd_znlyj5_e153_light
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 26%
              left: 63%
              width: 12%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/yangtai0.png
          - type: state-icon
            entity: light.hyd_znlyj5_e153_light
            style:
              top: 27%
              left: 62%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: light.yeelink_mbulb3_004f_light
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 63.5%
              left: 21%
              width: 36%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/zhuwo.png
          - type: state-icon
            entity: light.yeelink_mbulb3_004f_light
            style:
              top: 60%
              left: 15%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: light.yeelink_mbulb3_3884_light
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 72%
              left: 38.5%
              width: 21%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/ciwo.png
          - type: state-icon
            entity: light.yeelink_mbulb3_3884_light
            style:
              top: 67%
              left: 42%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light-multiple
          - type: image
            entity: switch.zimi_dhkg01_9672_switch
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 51%
              left: 76.3%
              width: 45.5%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/keting03.png
          - type: state-icon
            entity: switch.zimi_dhkg01_9672_switch
            style:
              top: 70%
              left: 80%
            tap_action:
              action: toggle
            icon: mdi:chandelier
          - type: image
            entity: light.yeelink_mbulb3_38a7_light
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 72%
              left: 59%
              width: 19%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/shufang.png
          - type: state-icon
            entity: light.yeelink_mbulb3_38a7_light
            style:
              top: 70%
              left: 55%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: switch.zimi_dhkg05_8bb0_middle_switch_service
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 54%
              left: 55%
              width: 39%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/zoulang.png
          - type: state-icon
            entity: switch.zimi_dhkg05_8bb0_middle_switch_service
            style:
              top: 53%
              left: 55%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: switch.zimi_dhkg05_8bb0_right_switch_service
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 42%
              left: 59%
              width: 19%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/weisheng1.png
          - type: state-icon
            entity: switch.zimi_dhkg05_8bb0_right_switch_service
            style:
              top: 43%
              left: 60%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
        width: 2930
  - title: 家庭纵览
    path: sd1
    icon: ''
    type: custom:grid-layout
    badges: []
    cards:
      - type: picture-elements
        image: /local/test/l_wan-0.jpg
        elements:
          - type: image
            entity: light.hyd_znlyj5_e153_light
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 26%
              left: 58%
              width: 7.5%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/yangtai0.png
          - type: state-icon
            entity: light.hyd_znlyj5_e153_light
            style:
              top: 27%
              left: 58%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: light.yeelink_mbulb3_004f_light
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 63.5%
              left: 32.3%
              width: 22%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/zhuwo.png
          - type: state-icon
            entity: light.yeelink_mbulb3_004f_light
            style:
              top: 60%
              left: 30%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: light.yeelink_mbulb3_3884_light
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 72%
              left: 43%
              width: 12.5%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/ciwo.png
          - type: state-icon
            entity: light.yeelink_mbulb3_3884_light
            style:
              top: 67%
              left: 42%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: switch.zimi_dhkg01_9672_switch
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 51%
              left: 66%
              width: 28%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/keting03.png
          - type: state-icon
            entity: switch.zimi_dhkg01_9672_switch
            style:
              top: 60%
              left: 68%
            tap_action:
              action: toggle
            icon: mdi:chandelier
          - type: image
            entity: light.yeelink_mbulb3_38a7_light
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 72%
              left: 55.4%
              width: 11.5%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/shufang.png
          - type: state-icon
            entity: light.yeelink_mbulb3_38a7_light
            style:
              top: 70%
              left: 55%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: switch.zimi_dhkg05_8bb0_middle_switch_service
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 54%
              left: 53%
              width: 22%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/zoulang.png
          - type: state-icon
            entity: switch.zimi_dhkg05_8bb0_middle_switch_service
            style:
              top: 53%
              left: 55%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
          - type: image
            entity: switch.zimi_dhkg05_8bb0_right_switch_service
            tap_action:
              action: none
            style:
              pointer-events: none
              top: 42%
              left: 55.5%
              width: 12%
              mix_blend_mode: lighten
            state_image:
              'off': /local/house/touming.png
              'on': /local/house/weisheng1.png
          - type: state-icon
            entity: switch.zimi_dhkg05_8bb0_right_switch_service
            style:
              top: 43%
              left: 55%
            tap_action:
              action: toggle
            icon: mdi:ceiling-light
title: Koisk Panel测试
