kiosk_mode:
  hide_sidebar: true
views:
  - title: Home
    theme: ios-dark-mode-dark-blue
    icon: ''
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: iframe
            url: /local/clock/index.html
            aspect_ratio: 44%
          - type: entity
            entity: sensor.mi_2186809020_message
            state_color: true
            name: 消息
          - type: picture
            image: http://192.168.101.57:8081/video
          - type: custom:weather-card
            entity: weather.liaoliaode_jia
            houer_forecast: false
            show_forecast: true
            icon: /hacsfiles/lovelace-colorfulclouds-weather-card/icons/animated/
            name: ''
            secondary_info_attribute: temperature
          - type: iframe
            url: >-
              https://embed.windy.com/embed2.html?lat=24.378&lon=109.439&detailLat=24.378&detailLon=109.439&width=650&height=450&zoom=11&level=surface&overlay=wind&product=ecmwf&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1
            aspect_ratio: 38%
      - type: vertical-stack
        cards:
          - type: picture-elements
            image: /local/house/wansh-0.png
            elements:
              - type: state-badge
                entity: sensor.liaoliaode_jia_gan_jue_wen_du
                title: 室内温度
                style:
                  top: 15%
                  left: 7%
              - type: image
                entity: light.hyd_znlyj5_e153_light
                tap_action:
                  action: none
                style:
                  pointer-events: none
                  top: 26%
                  left: 63%
                  width: 12%
                  mix_blend_mode: lighten
                state_image:
                  'off': /local/house/touming.png
                  'on': /local/house/yangtai0.png
              - type: state-icon
                entity: light.hyd_znlyj5_e153_light
                style:
                  top: 27%
                  left: 62%
                tap_action:
                  action: toggle
                icon: mdi:ceiling-light
              - type: image
                entity: light.yeelink_mbulb3_004f_light
                tap_action:
                  action: none
                style:
                  pointer-events: none
                  top: 63.5%
                  left: 21%
                  width: 36%
                  mix_blend_mode: lighten
                state_image:
                  'off': /local/house/touming.png
                  'on': /local/house/zhuwo.png
              - type: state-icon
                entity: light.yeelink_mbulb3_004f_light
                style:
                  top: 60%
                  left: 15%
                tap_action:
                  action: toggle
                icon: mdi:ceiling-light
              - type: image
                entity: light.yeelink_mbulb3_3884_light
                tap_action:
                  action: none
                style:
                  pointer-events: none
                  top: 72%
                  left: 38.5%
                  width: 21%
                  mix_blend_mode: lighten
                state_image:
                  'off': /local/house/touming.png
                  'on': /local/house/ciwo.png
              - type: state-icon
                entity: light.yeelink_mbulb3_3884_light
                style:
                  top: 67%
                  left: 42%
                tap_action:
                  action: toggle
                icon: mdi:ceiling-light-multiple
              - type: image
                entity: switch.zimi_dhkg01_9672_switch
                tap_action:
                  action: none
                style:
                  pointer-events: none
                  top: 51%
                  left: 76.3%
                  width: 45.5%
                  mix_blend_mode: lighten
                state_image:
                  'off': /local/house/touming.png
                  'on': /local/house/keting03.png
              - type: state-icon
                entity: switch.zimi_dhkg01_9672_switch
                style:
                  top: 70%
                  left: 80%
                tap_action:
                  action: toggle
                icon: mdi:chandelier
              - type: image
                entity: light.yeelink_mbulb3_38a7_light
                tap_action:
                  action: none
                style:
                  pointer-events: none
                  top: 72%
                  left: 59%
                  width: 19%
                  mix_blend_mode: lighten
                state_image:
                  'off': /local/house/touming.png
                  'on': /local/house/shufang.png
              - type: state-icon
                entity: light.yeelink_mbulb3_38a7_light
                style:
                  top: 70%
                  left: 55%
                tap_action:
                  action: toggle
                icon: mdi:ceiling-light
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-template-card
                primary: 亮灯
                secondary: >-
                  {{states.light | selectattr('state', 'eq', 'on') |
                  selectattr('attributes.friendly_name', 'search', '...') | list
                  | count }}
                icon: mdi:lightbulb
                icon_color: yellow
                tap_action:
                  action: call-service
                  service: xiaomi_miot.intelligent_speaker
                  target: {}
                  data:
                    execute: true
                    silent: true
                    throw: true
                    entity_id: media_player.xiaomi_l05c_009b_play_control
                    text: 关闭所有灯
              - type: custom:mushroom-template-card
                primary: 空调
                secondary: >-
                  {{states.climate | rejectattr('state', 'eq', 'off') |
                  rejectattr('state', 'eq', 'unavailable') | list | count  }}
                icon: mdi:air-conditioner
                icon_color: green
                tap_action:
                  action: call-service
                  service: xiaomi_miot.intelligent_speaker
                  target: {}
                  data:
                    execute: true
                    silent: true
                    throw: true
                    entity_id: media_player.xiaomi_l05c_009b_play_control
                    text: 关闭所有空调
              - type: custom:mushroom-template-card
                primary: 风扇
                secondary: >-
                  {{states.fan | selectattr('state', 'eq', 'on') |
                  selectattr('attributes.friendly_name', 'search', '风扇') | list
                  | count }}
                icon: mdi:ceiling-fan
                icon_color: blue
                tap_action:
                  action: call-service
                  service: xiaomi_miot.intelligent_speaker
                  target: {}
                  data:
                    execute: true
                    entity_id: media_player.xiaomi_l05c_009b_play_control
                    text: 关闭所有风扇
                    silent: true
                    throw: true
          - type: media-control
            entity: media_player.xiaomi_l05c_009b_play_control
          - type: media-control
            entity: media_player.xiaomi_v1_e339_play_control
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.liaoliaode_jia_yu_liang
                name: 降雨量
                line_color: blue
                line_width: 8
                font_size: 75
              - type: custom:mini-graph-card
                entities:
                  - sensor.liaoliaode_jia_zi_wai_xian
                line_color: '#e74c3c'
                name: 紫外线
                line_width: 8
                font_size: 75
              - type: custom:mini-graph-card
                entities:
                  - sensor.liaoliaode_jia_shi_du
                line_color: var(--accent-color)
                line_width: 8
                name: 湿度
                font_size: 75
          - type: custom:mini-graph-card
            entities:
              - sensor.liaoliaode_jia_wen_du
              - sensor.liaoliaode_jia_gan_jue_wen_du
              - sensor.liaoliaode_jia_shu_gua_zhi_shu
          - type: media-control
            entity: media_player.jmgo_sopd
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: zone.home
                  - entity: sensor.iphone_battery_level
                    name: 手机电量
                  - entity: sensor.iphone_steps
                    name: 今日步数
                  - entity: sensor.iphone_storage
                    name: 存储空间
                header:
                  type: picture
                  image: /local/m4.png
                  tap_action:
                    action: none
                  hold_action:
                    action: none
              - type: entities
                entities:
                  - entity: sensor.loock_s30_0629_battery_level
                    name: 鹿锁电量
                  - entity: sensor.loock_s30_0629_lock
                    name: 👋
                  - entity: sensor.loock_s30_0629_lock_action
                    name: 途径
                  - entity: sensor.loock_s30_0629_timestamp
                    name: 时间
          - type: grid
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: more-info
                show_state: true
                icon: mdi:television
                entity: media_player.miir_ir01_3170_ir_tv_control
                name: 电视
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: media_player.miir_ir01_6128_ir_projector_control
                show_state: false
                name: 坚果投影仪
              - show_name: true
                show_icon: true
                show_state: true
                entity: switch.minij_v8_f83c_switch_status
                icon: mdi:washing-machine
                name: 洗衣机
                type: button
                tap_action:
                  action: navigate
                  navigation_path: http://192.168.101.2:8123/dashboard-home/test
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: switch.zimi_dhkg01_9672_switch
                icon: mdi:light-switch
                show_state: true
                theme: ios-dark-mode-dark-green
                name: 客厅吸顶灯
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: xiaomi_miot.intelligent_speaker
                  target: {}
                  data:
                    execute: true
                    silent: true
                    throw: true
                    entity_id: media_player.xiaomi_l05c_009b_play_control
                    text: 播放因为
                entity: media_player.xiaomi_l05c_009b_play_control
                show_state: true
                name: 小爱同学
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: light.hyd_znlyj5_e153_light
                show_state: false
                name: 晾衣架的灯
                icon: mdi:light-recessed
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.popup
                    data:
                      title: 客厅空调
                      content:
                        type: thermostat
                        entity: climate.miir_ir02_7712_ir_aircondition_control
                entity: climate.miir_ir02_7712_ir_aircondition_control
                show_state: true
                name: 客厅空调
              - show_name: true
                show_icon: true
                type: button
                entity: climate.lumi_mcn02_aee4_air_conditioner
                tap_action:
                  action: ''
                show_state: true
                name: 主卧空调
              - show_name: true
                show_icon: true
                type: button
                entity: climate.lumi_mcn02_0a06_air_conditioner
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.popup
                    data:
                      title: 次卧空调
                      content:
                        type: thermostat
                        entity: climate.lumi_mcn02_0a06_air_conditioner
                show_state: true
                name: 次卧空调
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: light.yeelink_mbulb3_004f_light
                show_state: true
                name: 主卧的落地灯
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: light.yeelink_mbulb3_3884_light
                show_state: true
                name: 次卧落地灯
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: light.yeelink_mbulb3_38a7_light
                show_state: true
                name: 书房落地灯
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: switch.lumi_acn032_14bb_left_switch_service
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: fan.dmaker_p9_431d_fan
          - type: history-graph
            entities:
              - sun.sun
          - type: entity
            entity: sensor.moon_phase
  - title: 洗衣机页面
    path: test
    icon: mdi:washing-machine
    subview: true
    badges: []
    cards:
      - type: entities
        entities:
          - entity: button.minij_v8_f83c_start_wash
            name: 开始洗衣
          - entity: sensor.minij_v8_f83c_washer
            name: 当前状态
          - entity: switch.minij_v8_f83c_washer_status
          - entity: select.minij_v8_f83c_mode
            name: 选择模式
          - entity: select.minij_v8_f83c_rinsh_times
          - entity: select.minij_v8_f83c_drying_level
            name: 干燥温度
          - entity: select.minij_v8_f83c_spin_speed
            name: 转速
          - entity: select.minij_v8_f83c_target_temperature
            name: 水温
          - entity: select.minij_v8_f83c_target_water_level
            name: 水位
        title: 洗衣机
        header:
          type: picture
          image: >-
            https://www.home-assistant.io/images/lovelace/header-footer/balloons-header.png
          tap_action:
            action: none
          hold_action:
            action: none
title: Liao‘s Home
